# Generated by Django 3.2.5 on 2023-11-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('DOLL', 'Doll'), ('PUZZLE', 'Puzzle'), ('ELECTRONIC', 'Electronic'), ('GAME', 'Game'), ('BASIC', 'Basic')], default='BASIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
